server:
    port: 9093
spring:
    application:
        name: appointment-service
    jpa:
        generate-ddl: false
        hibernate:
            ddl-auto: none

eureka:
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:8761/eureka/
