server:
    port: 8889
spring:
    application:
        name: config-server-client
eureka:
    client:
        serviceUrl:
          defaultZone: http://localhost:8762/eureka/

message: Hello config server client!!!
