server:
    port: 9092
spring:
    application:
        name: person-service
    jpa:
        generate-ddl: false
        hibernate:
            ddl-auto: none
eureka:
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:9091/eureka/
